# -*- coding: utf-8 -*-
"""Exercícios6PY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11nNMaGzjLKIPx1AiXZ8JfalhODEKobin
"""

# EXERCÍCIO 1
for n in range(1,6):
 print(n)

# EXERCÍCIO 2
m_l = [1,2,3,4,5]
f_e = m_l[4]
print(f_e)

# EXERCÍCIO 3
m_l = [1,2,3,4,5]
m_l.append(6)
print(m_l)

# EXERCÍCIO 4
m_l = [1,2,3,4,5]
m_l.remove(3)
print(m_l)

# EXERCÍCIO 6

frutas = ['pera','banana','maça']
for numero in frutas:
    print(numero)

# EXERCÍCIO 7

numeros = [1,3,6,5,25,16]

if (numeros ==5):

# EXERCÍCIO 5
frutas = 'pera','banana','maça'
n1 = 0
for numeros in frutas:
  n1+=1
  print(n1,numeros)

numeros = [10,20,5,30,12,11]
if 5 in numeros:
    print("O número 5 está na lista.")
else:
    print("O número 5 não está na lista.")